services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb, sts
    ports:
      - "4566:4566"

  app:
    build: ./src
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
