name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        run: docker compose up -d

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Set up Python environment
        run: |
          export PYTHONPATH="${PYTHONPATH}:./src"
      
      - name: List files
        run: ls -R  
        
      - name: Debug Python Path
        run: echo $PYTHONPATH
      - name: Run tests with pytest
        env:
            PYTHONPATH: ./src  
        run: pytest tests/ --maxfail=5 --disable-warnings --cov=src
        
      - name: Run Flake8 (PEP8 linter)
        run: flake8 src tests --max-line-length=88 --exclude=venv,.git,__pycache__

      - name: Run Black (autoformatter check)
        run: black --check src tests

      - name: Run isort (import sorting check)
        run: isort --check src tests

